### ISSUE TITLE
Order of Areas, Objectives, and KRs

### ISSUE THREAD

**Issue by beccamc** [microsoft/OKR-Hub#50]
Order of all of our data is random now. Should it be alphabetical?  Allow users to determine order?

**Comment by beccamc** [comment]
@edwindotcom What are your thoughts on the order of our data?

**Comment by edwindotcom** [comment]
Product Areas: Alphabetical - since we want to find your product area
OKRs for Product Area - Ideally authors should have full control of the order, so maybe 'rank' or 'priority' 1-100.
