### ISSUE TITLE
Detail > pill selector - avoid jumping on click

### ISSUE THREAD

**Issue by edwindotcom** [microsoft/OKR-Hub#75]

**Comment by edwindotcom** [comment]
Pills cause line break if KR is long. This will get fixed if we have a column on the for status and score. 
<img width="362" alt="Screen Shot 2019-08-01 at 10 42 33 AM" src="https://user-images.githubusercontent.com/3698618/62315093-6f093f00-b449-11e9-82d2-3552ebc11bbc.png">

**Comment by paterasMSFT** [comment]
@edwindotcom I've reduced the jump significantly. Eliminating it is proving difficult, and likely not worth spending much more time on, but take a look and let me know what you think.
